# This file is meant to be run without console echos active (ctrl+shift+s)!
# Run this file with the keyboard shortcut given above to print the fully formatted
# solution text to the console.

source("globalFunctionRepository.R")

file_header(1, 4)
cat("The problem: R-functions\n")
cat("a) trees is the R Dataset Package containing Diameter, Height and Volume for 31 Black ")
cat("Cherry trees. Using R define a vector h that contains the values of the column Height ")
cat("and define a vector v that contains the values of the column Volume from the dataset ")
cat("trees. Use the command table(h) to obtain the frequency table of the vector h. What ")
cat("are the outputs of the commands summary(h) and factor(h)? Compute the sample ")
cat("means mean() and the sample variances var() for both vectors. Use the command ")
cat("plot() to plot the points (h, v).\n\n")
cat("b) Consider the curve given by the parametrization t -> (e^(-t/8) * cos(2t), ")
cat("e^(t/5) + sin(3t)) for 0 <= t <= 5*pi. Use plot() to plot the curve and ")
cat("dev.print() to save the result as a pdf file.")
cat("\n\n", string_divider, "\n\n")
# -----------------------------------------------------------------------------#
cat("SOLUTION for a)\n")

data("trees") # Loads the dataset "trees" into a variable called "trees"

# Define vectors for height and volume
h <- trees$Height
v <- trees$Volume

cat("Vector h:\n", h)
cat("\n\nVector v:\n", v)
cat("\n\nFrequency table for h:\n")
print(table(h))

cat("\nOutput of summary(h):\n")
print(summary(h))

cat("\nExplanation: The function summary() can be used to generate summaries of various ")
cat("objects in R. Used on a vector (as we have done here), summary calculates the ")
cat("minimum and maximum values of the vector, the 1st (= x_0.25) and 3rd (= x_0.75) ")
cat("quartiles, mean and median. In this way, summary() can quickly get some basic ")
cat("descriptive statistics about an vector of integer values.\n\n")

cat("Output of factor(h):\n")
print(factor(h))

cat("\nExplanation: The function factor() categorizes data and stores it as levels. ")
cat("Applied to vectors, this basically means that factor() simply lists all distinct/unique ")
cat("elements of the vector ordered - but only once per element. We can perhaps see this more easily if ")
cat("we apply factor() to a vector with something other than integers, for example with letters instead:\n\n")

cat("factor(c(\"a\", \"a\", \"a\", \"b\", \"c\", \"a\")):\n")
print(factor(c("a", "a", "a", "a", "b", "c", "a")))

cat("\nWe see that factor() lists \"a b c\" in lexicographic order as Levels, since our vector was built from ")
cat("multiples of these three unique elements.")

cat("\n\nAs for sample means and sample variances for both vectors h and v, we can ")
cat("easily compute them in R:\n\n")
cat("mean(h):", mean(h), "\n")
cat("var(h):", var(h), "\n")
cat("mean(v):", mean(v), "\n")
cat("var(v):", var(v), "\n\n")

cat("For the plot generated by the following line, please see the resulting graphic\n")
cat("  (plot command used: plot(h, v, type=\"p\", main=\"Plot for (h, v) of trees\", xlab=\"h (height)\", ylab=\"v (volume)\"))")
plot(h, v, type="p", main="Plot for (h, v) of trees", xlab="h (height)", ylab="v (volume)")

cat("\n\nEND OF SOLUTION FOR A")
cat("\n\n", string_divider, "\n\n")
# -----------------------------------------------------------------------------#
cat("SOLUTION for b)\n")
cat("See \"problem 1b.pdf\" for the resulting plot\n")
# Define Euler's number
e <- exp(1)

# Define functions for x- and y-coordinates from the parametric representation given
x_coord <- function(t) e^(-(t/8)) * cos(2*t)
y_coord <- function(t) e^(t/5) * sin(3*t)

# Package coordinate functions together with the desired range for parameter t into a dataframe
dat <- data.frame(t=seq(0, 5*pi, 0.01))
dat$x=x_coord(dat$t)
dat$y=y_coord(dat$t)

# Define title with mathematical expressions for plot
plot_title <- expression(paste(t %->% e^-frac(t, 8) %*% cos(2*t), ", ", e^frac(t,5) %*% sin(3*t), "      for 0 <= t <= ", 5*pi))

# Plot curve with fine-tuned x- and y-axis so that the image is centered on the coordinate
# origin with symmetric x- and y-axis labeling
plot(dat$x, dat$y, type="l", main=plot_title, xlab="x", ylab="y", xlim=c(-1, 1), xaxp=c(-1, 1, 20), ylim=c(-20, 20), yaxp = c(-20, 20, 8))

# Draw lines through the origin of the coordinate system to have a visual anchor
abline(h = 0, col="blue", lty=2)
abline(v = 0, col="blue", lty=2)

dev.print(device = pdf, file="problem 1b.pdf")

cat("\n\nEND OF SOLUTION FOR B")
cat("\n\nEND OF SOLUTION FILE")

# END OF FILE