# This file is meant to be run without console echos active (ctrl+shift+s)!
# Run this file with the keyboard shortcut given above to print the fully formatted
# solution text to the console.

source("globalFunctionRepository.R")

file_header(1, 1)
cat("The problem: Independence\n")
cat("Let A and B be two independent events.\n\n")
cat("Problem a)\n")
cat("Prove that the complement of A (A') and the complement of B (B') are also independent.\n\n")
cat("SOLUTION\n")
cat("We know that A and B are independent, thus the following is true (\"AND\" stands for the ")
cat("set theoretical symbol for \"Intersection\"):\n\n")
cat("\tP(A AND B) = P(A) * P(B)\n\n")
cat("To show that A' and B' are also independent, we have to show that the following holds:\n\n")
cat("\tP(A' AND B') = P(A') * P(B')\n\n")
cat("We will now show that the formula above is true (\"OR\" stands for the ")
cat("set theoretical symbol for \"Union\"):\n\n")
cat("\tP(A) = P((A AND B) OR (A AND B'))\t[Since B and B' are mutually exclusive]\n")
cat("\t=> P(A) = P(A AND B) + P(A AND B')\t[Third axiom of kolmogoroff, since both are mutually exlusive]\n")
cat("\t=> P(A) = P(A)P(B) + P(A AND B')\t[Definition of independence]\n")
cat("\t=> P(A AND B') = P(A) - P(A)P(B)\t[Basic algebra]\n")
cat("\t=> P(A AND B') = P(A) * (1 - P(B))\t[Take P(A) out of brackets on right side]\n")
cat("\t=> P(A AND B') = P(A) * P(B')\t\t[Since P(B') = 1 - P(B)]\n\n")
cat("Now remember P(A AND B') = P(B' AND A)\t[Symmetry of independence]\n")
cat("Thus, we can start the same process with P(B') = P((B' AND A) OR (B' AND A') ")
cat("and arrive at the conclusion P(B' AND A') = P(A') * P(B'), which is what we ")
cat("wanted to show.\n\n")
cat("\t[QED]\n\n")
cat("Another interesting way to show this is the follwing:\n\n")
cat("\tP(A|B) = P(A) = P(A|B') => P(B'|A) = P(B') = P(B'|A')\n")
cat("\tP(B|A) = P(B) = P(B|A') => P(A'|B) = P(A') = P(A'|B')\n\n")
cat("\t[QED]\n\n")
cat("And a third way:\n\n")
cat("\tP(A' AND B') = P((A OR B)')\t\t[De Morgan's law]\n")
cat("\t= 1 - P(A OR B)\t\t\t\t[Definition of complement]\n")
cat("\t= 1 - P(A) - P(B) + P(A AND B)\t\t[Since P(A OR B) = P(A) + P(B) - P(A AND B)]\n")
cat("\t= 1 - P(A) - P(B) + (P(A) * P(B))\t[Since P(A AND B) = P(A) * P(B)]\n")
cat("\t= (1 - P(B)) * (1 - P(A))\t\t[Some algebra]\n")
cat("\t= P(B') * P(A')\t\t\t\t[Obvious by now]\n\n")
cat("\t[QED]\n\n")

cat("\n\n")
cat("Problem b)\n")
cat("If we additionally know that P(A|B) = 0.6 and P(B|A) = 0.3, compute the probabilities ")
cat("of the following events\n")
cat("\t(i) at most one of A or B\n")
cat("\t(ii) either A or B but not both\n\n")
cat("SOLUTION\n")
cat("for (i):\n")
cat("Since A and B are independent, it holds that: P(A|B) = P(A) = 0.6, P(B|A) = P(B) = 0.3\n")
cat("\"At most one of A or B\" means either A happens, B happens or neither happens. ")
cat("So we just have to calculate the possibility of not A AND B happening:\n\n")
cat("\tP((A AND B)') = 1 - P(A AND B) = 1 - (P(A) * P(B)) = 1 - (0.6 * 0.3) =", 1 - (0.6 * 0.3),"\n\n")
cat("for (ii):\n")
cat("\"either A or B but not both\" means A XOR B, which here is equal to (A OR B) ")
cat(" - (A AND B), and thus:\n\n")
cat("\tP((A XOR B)) = P(A OR B) - P(A AND B)\n")
cat("\t= P(A) + P(B) - (P(A) * P(B)) - (P(A) * P(B))\n")
cat("\t= 0.6 + 0.3 - (0.6 * 0.3) - (0.6 * 0.3) =",  0.6 + 0.3 - (0.6 * 0.3) - (0.6 * 0.3) ,"\n\n")

cat("END OF SOLUTION FILE")

# END OF SOLUTION
# END OF FILE