# This file is meant to be run without console echos active (ctrl+shift+s)!
# Run this file with the keyboard shortcut given above to print the fully formatted
# solution text to the console.
sim_iterations <- 100000

source("globalFunctionRepository.R")
source("problem 3b.R")

file_header(3, 2)
cat("The problem: Density and distribution function\n")
cat("Let X a continuous random variable with the probability density function (pdf):\n\n")
cat("\tf_X(x) = (b ln(x)) / x\t\tif x in (e, e^2)\n")
cat("\tf_X(x) = 0\t\t\totherwise\n")
cat("\t  with b as positive, real constant\n\n")
cat("\ta) Determine the value of b.\n")
cat("\tb) Find the cumulative distribution function of X.\n")
cat("\tc) Compute the expectation of Z = 2(X^2) + 5.\n")
cat("\n\n", string_divider, "\n\n")
cat("SOLUTION FOR a)\n")
cat("The pdf of a continuous random variable is the pendant to the pmf of a discrete ")
cat("random variable. The differences are: The pdf f(x) is not a probability, it ")
cat("has to be integrated to yield a probability, and there is no restriction of ")
cat("course that f(x) is less than or equal to 1. f is nonnegative (f(x) >= 0) ")
cat("and the area under f is 1 (integral_of(f(x) dx) = 1).\n\n")
cat("With the last snippet of information, we see that integral_of(f(x) dx) = 1, ")
cat("and since f_X(x) = 0 for all x not in (e, e^2), we have:\n\n")
cat("\tintegral_from_e_to_e^2_of(((b ln(x)) / x) dx) = 1\n")
cat("\t<=> b * integral_from_e_to_e^2_of((ln(x) / x) dx) = 1\n")
cat("\t<=> b = 1 / integral_from_e_to_e^2_of((ln(x) / x) dx)\n\n")
cat("The only thing left now is to calculate this definite integral:\n\n")
cat("\tAfter u-substitution and a bit of calculation we arrive at:\n")
cat("\t   b = 2/3\n")
cat("\t(see \"problem 3c.jpg\" for a full treatment of this calculation)\n\n")
cat("END OF SOLUTION FOR a)")
cat("\n\n", string_divider, "\n\n")
cat("SOLUTION FOR b) [Find the cumulative distribution function of X.]\n")
cat("The cumulative distribution function for a continuous random variable is ")
cat("given as:\n")
cat("\tF(X) = P(X <= x) = integral_from_minusInf_to_x_of(f(t) dt)\n\n")
cat("Thus the cdf here is:\n\n")
cat("\tF(X) = P(X <= x) = integral_from_e_to_e^2_of(((b ln(x)) / x) dx) OR 0 if x <= e ")
cat("OR 1 if x >= e^2\n\n")
cat("END OF SOLUTION FOR b)")
cat("\n\n", string_divider, "\n\n")
cat("SOLUTION FOR c) [Compute the expectation of Z = 2(X^2) + 5.]\n")
cat("The expected value of X for a continuous random variable is defined as:\n\n")
cat("\tE(X) = integral_of_minusInf_to_positiveInf_of(x * f(x) dx)\n\n")
cat("With this in mind, we calculate:\n\n")
cat("\tE(Z) = E(2(X^2) + 5) = 2 * E(X^2) + 5\t[Since E(aX + b) = a * E(X) + b]\n\n")
cat("Lets plug these values into the definition for the expected value (and ")
cat("abbreviate \"integral\" as \"igrl\"):\n\n")
cat("\tigrl_of_minusInf_to_positiveInf(2 * x^2 * f(x) dx) = 5 + 2 * igrl_of_e_to_e^2(x^2 * b * ln(x)/x dx)\n")
cat("\t= 5 + 2 * 2/3 * igrl_of_e_to_e^2(x^2 * ln(x)/x dx)\n")
cat("\t= 5 + 4/3 * igrl_of_e_to_e^2(x * ln(x) dx)\n")
cat("\t= 5 + 4/3 * igrl_of_e_to_e^2(x * ln(x) dx)\n\n")
cat("Lets now apply integration by parts to the integral:\n\n")
cat("\t[Integration by parts definition: igrl_of(uv') = uv - igrl_of(u'v)]\n")
cat("\t[Here: u = ln(x), v' = x, u' = d/dx ln(x) = 1/x, v = igrl_of(x dx) = x^2/2]\n\n")
cat("\tln(x) * x^2/2 - igrl_of((1/x) * x^2/2 dx)\t[from e to e^2]\n")
cat("\t= ((x^2 * ln(x)) / 2) - igrl_of(x/2 dx)\t\t[from e to e^2]\n")
cat("\t= 1/2 * (x^2 * ln(x) - x^2/2)\t\t\t[from e to e^2]\n\n")
cat("Calculate boundaries:\n\n")
cat("\tlim(x -> e+)(1/2 * (x^2 * ln(x) - x^2/2)) = 1/2 * (e^2 * ln(e) - e^2/2)\n")
cat("\t1/2 * (e^2 - e^2/2) = (e^2 - e^2/2) / 2 = ((2 * e^2)/2 - e^2/2) / 2 = (e^2/2) / 2 = e^2/4\n\n")
cat("\tlim(x -> e^2-)(1/2 * (x^2 * ln(x) - x^2/2)) = 1/2 * (e^4 * ln(e^2) - e^4/2)\n")
cat("\t= (2e^4 - e^4/2) / 2 = (3 * e^4)/(2*2) = (3 * e^4)/4\n\n")
cat("Because igrl_from_a_to_b_of(f(x) dx) = lim(x -> b-)(F(X)) - lim(x -> a+)(F(X)):\n\n")
cat("\tE(Z) = 5 + 4/3 * ((3 * e^4)/4 - e^2/4) = 5 + (((3 * e^4)/4 - e^2/4) * 4) / (4*3)\t[Cancel 4]\n")
cat("\t= 5 + (3 * e^4 - e^2) / 3 = 5 + ")
temp <- (3 * exp(4) - exp(2)) / 3
cat(temp, "=", 5 + temp, "\n\n")

cat("END OF SOLUTION FOR c)\n\n")

cat("END OF SOLUTION FILE")

# END OF PROBLEM B SOLUTION
# END OF FILE